/*
 * Copyright (c) 2025 Ambiq Micro Inc.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_DRIVERS_BLUETOOTH_HCI_APOLLOX_IPC_SUPPORT_H_
#define ZEPHYR_DRIVERS_BLUETOOTH_HCI_APOLLOX_IPC_SUPPORT_H_

#include <stdint.h>
#include <zephyr/bluetooth/addr.h>
#include <zephyr/bluetooth/hci_types.h>

/*
 * 510L controller feature definitions
 */
#define APOLLO_330P_510L_LE_SUP_FEAT(bit) (1ULL << (bit))

#define APOLLO_330P_510L_HCI_LE_SUP_FEAT_ENCRYPTION APOLLO_330P_510L_LE_SUP_FEAT(BT_LE_FEAT_BIT_ENC)
#define APOLLO_330P_510L_HCI_LE_SUP_FEAT_CONN_PARAM_REQ_PROC                                       \
	APOLLO_330P_510L_LE_SUP_FEAT(BT_LE_FEAT_BIT_CONN_PARAM_REQ)
#define APOLLO_330P_510L_HCI_LE_SUP_FEAT_EXT_REJECT_IND                                            \
	APOLLO_330P_510L_LE_SUP_FEAT(BT_LE_FEAT_BIT_EXT_REJ_IND)
#define APOLLO_330P_510L_HCI_LE_SUP_FEAT_SLV_INIT_FEAT_EXCH                                        \
	APOLLO_330P_510L_LE_SUP_FEAT(BT_LE_FEAT_BIT_PER_INIT_FEAT_XCHG)
#define APOLLO_330P_510L_HCI_LE_SUP_FEAT_LE_PING APOLLO_330P_510L_LE_SUP_FEAT(BT_LE_FEAT_BIT_PING)
#define APOLLO_330P_510L_HCI_LE_SUP_FEAT_DATA_LEN_EXT                                              \
	APOLLO_330P_510L_LE_SUP_FEAT(BT_LE_FEAT_BIT_DLE)
#define APOLLO_330P_510L_HCI_LE_SUP_FEAT_PRIVACY                                                   \
	APOLLO_330P_510L_LE_SUP_FEAT(BT_LE_FEAT_BIT_PRIVACY)
#define APOLLO_330P_510L_HCI_LE_SUP_FEAT_EXT_SCAN_FILT_POLICY                                      \
	APOLLO_330P_510L_LE_SUP_FEAT(BT_LE_FEAT_BIT_EXT_SCAN)
#define APOLLO_330P_510L_HCI_LE_SUP_FEAT_LE_2M_PHY                                                 \
	APOLLO_330P_510L_LE_SUP_FEAT(BT_LE_FEAT_BIT_PHY_2M)
#define APOLLO_330P_510L_HCI_LE_SUP_FEAT_LE_CODED_PHY                                              \
	APOLLO_330P_510L_LE_SUP_FEAT(BT_LE_FEAT_BIT_PHY_CODED)
#define APOLLO_330P_510L_HCI_LE_SUP_FEAT_LE_EXT_ADV                                                \
	APOLLO_330P_510L_LE_SUP_FEAT(BT_LE_FEAT_BIT_EXT_ADV)
#define APOLLO_330P_510L_HCI_LE_SUP_FEAT_LE_PER_ADV                                                \
	APOLLO_330P_510L_LE_SUP_FEAT(BT_LE_FEAT_BIT_PER_ADV)
#define APOLLO_330P_510L_HCI_LE_SUP_FEAT_CH_SEL_2                                                  \
	APOLLO_330P_510L_LE_SUP_FEAT(BT_LE_FEAT_BIT_CHAN_SEL_ALGO_2)
#define APOLLO_330P_510L_HCI_LE_SUP_FEAT_MIN_NUM_USED_CHAN                                         \
	APOLLO_330P_510L_LE_SUP_FEAT(BT_LE_FEAT_BIT_MIN_USED_CHAN_PROC)
#define APOLLO_330P_510L_HCI_LE_SUP_FEAT_PAST_SENDER                                               \
	APOLLO_330P_510L_LE_SUP_FEAT(BT_LE_FEAT_BIT_PAST_SEND)
#define APOLLO_330P_510L_HCI_LE_SUP_FEAT_PAST_RECIPIENT                                            \
	APOLLO_330P_510L_LE_SUP_FEAT(BT_LE_FEAT_BIT_PAST_RECV)
#define APOLLO_330P_510L_HCI_LE_SUP_FEAT_SCA_UPDATE                                                \
	APOLLO_330P_510L_LE_SUP_FEAT(BT_LE_FEAT_BIT_SCA_UPDATE)
#define APOLLO_330P_510L_HCI_LE_SUP_FEAT_REMOTE_PUB_KEY_VALIDATION                                 \
	APOLLO_330P_510L_LE_SUP_FEAT(BT_LE_FEAT_BIT_REMOTE_PUB_KEY_VALIDATE)
#define APOLLO_330P_510L_HCI_LE_SUP_FEAT_CIS_MASTER                                                \
	APOLLO_330P_510L_LE_SUP_FEAT(BT_LE_FEAT_BIT_CIS_CENTRAL)
#define APOLLO_330P_510L_HCI_LE_SUP_FEAT_CIS_SLAVE                                                 \
	APOLLO_330P_510L_LE_SUP_FEAT(BT_LE_FEAT_BIT_CIS_PERIPHERAL)
#define APOLLO_330P_510L_HCI_LE_SUP_FEAT_ISO_BROADCASTER                                           \
	APOLLO_330P_510L_LE_SUP_FEAT(BT_LE_FEAT_BIT_ISO_BROADCASTER)
#define APOLLO_330P_510L_HCI_LE_SUP_FEAT_ISO_SYNC_RECEIVER                                         \
	APOLLO_330P_510L_LE_SUP_FEAT(BT_LE_FEAT_BIT_SYNC_RECEIVER)
#define APOLLO_330P_510L_HCI_LE_SUP_FEAT_POWER_CONTROL_REQUEST                                     \
	APOLLO_330P_510L_LE_SUP_FEAT(BT_LE_FEAT_BIT_PWR_CTRL_REQ)
#define APOLLO_330P_510L_HCI_LE_SUP_FEAT_POWER_CHANGE_IND                                          \
	APOLLO_330P_510L_LE_SUP_FEAT(BT_LE_FEAT_BIT_PWR_CHG_IND)
#define APOLLO_330P_510L_HCI_LE_SUP_FEAT_PATH_LOSS_MONITOR                                         \
	APOLLO_330P_510L_LE_SUP_FEAT(BT_LE_FEAT_BIT_PATH_LOSS_MONITOR)
#define APOLLO_330P_510L_HCI_LE_SUP_FEAT_PRR_ADV_ADI                                               \
	APOLLO_330P_510L_LE_SUP_FEAT(BT_LE_FEAT_BIT_PER_ADV_ADI_SUPP)
#define APOLLO_330P_510L_HCI_LE_SUP_FEAT_SUBRATING                                                 \
	APOLLO_330P_510L_LE_SUP_FEAT(BT_LE_FEAT_BIT_CONN_SUBRATING)
#define APOLLO_330P_510L_HCI_LE_SUP_FEAT_SUBRATING_HOST_SUPPORT                                    \
	APOLLO_330P_510L_LE_SUP_FEAT(BT_LE_FEAT_BIT_CONN_SUBRATING_HOST_SUPP)
#define APOLLO_330P_510L_HCI_LE_SUP_FEAT_CHAN_CLASSIFICATION                                       \
	APOLLO_330P_510L_LE_SUP_FEAT(BT_LE_FEAT_BIT_CHANNEL_CLASSIFICATION)
#define APOLLO_330P_510L_HCI_LE_SUP_FEAT_ADV_CODING_SELECTION                                      \
	APOLLO_330P_510L_LE_SUP_FEAT(BT_LE_FEAT_BIT_ADV_CODING_SEL)
#define APOLLO_330P_510L_HCI_LE_SUP_FEAT_ADV_CODING_SELECTION_HOST_SUPPORT                         \
	APOLLO_330P_510L_LE_SUP_FEAT(BT_LE_FEAT_BIT_ADV_CODING_SEL_HOST)
#define APOLLO_330P_510L_HCI_LE_SUP_FEAT_PER_ADV_WITH_RESP_ADVERTISER                              \
	APOLLO_330P_510L_LE_SUP_FEAT(BT_LE_FEAT_BIT_PAWR_ADVERTISER)
#define APOLLO_330P_510L_HCI_LE_SUP_FEAT_PER_ADV_WITH_RESP_SCANNER                                 \
	APOLLO_330P_510L_LE_SUP_FEAT(BT_LE_FEAT_BIT_PAWR_SCANNER)

#define APOLLO_330P_510L_LL_FEATURES_BYTE0                                                         \
	(APOLLO_330P_510L_HCI_LE_SUP_FEAT_ENCRYPTION |                                             \
	 APOLLO_330P_510L_HCI_LE_SUP_FEAT_CONN_PARAM_REQ_PROC |                                    \
	 APOLLO_330P_510L_HCI_LE_SUP_FEAT_EXT_REJECT_IND |                                         \
	 APOLLO_330P_510L_HCI_LE_SUP_FEAT_SLV_INIT_FEAT_EXCH |                                     \
	 APOLLO_330P_510L_HCI_LE_SUP_FEAT_LE_PING |                                                \
	 APOLLO_330P_510L_HCI_LE_SUP_FEAT_DATA_LEN_EXT |                                           \
	 APOLLO_330P_510L_HCI_LE_SUP_FEAT_PRIVACY |                                                \
	 APOLLO_330P_510L_HCI_LE_SUP_FEAT_EXT_SCAN_FILT_POLICY)

#define APOLLO_330P_510L_LL_FEATURES_BYTE1                                                         \
	(APOLLO_330P_510L_HCI_LE_SUP_FEAT_LE_2M_PHY |                                              \
	 APOLLO_330P_510L_HCI_LE_SUP_FEAT_LE_CODED_PHY |                                           \
	 APOLLO_330P_510L_HCI_LE_SUP_FEAT_LE_EXT_ADV |                                             \
	 APOLLO_330P_510L_HCI_LE_SUP_FEAT_LE_PER_ADV | APOLLO_330P_510L_HCI_LE_SUP_FEAT_CH_SEL_2)

#define APOLLO_330P_510L_LL_FEATURES_BYTE2 (APOLLO_330P_510L_HCI_LE_SUP_FEAT_MIN_NUM_USED_CHAN)

#define APOLLO_330P_510L_LL_FEATURES_BYTE3                                                         \
	(APOLLO_330P_510L_HCI_LE_SUP_FEAT_PAST_SENDER |                                            \
	 APOLLO_330P_510L_HCI_LE_SUP_FEAT_PAST_RECIPIENT |                                         \
	 APOLLO_330P_510L_HCI_LE_SUP_FEAT_SCA_UPDATE |                                             \
	 APOLLO_330P_510L_HCI_LE_SUP_FEAT_REMOTE_PUB_KEY_VALIDATION |                              \
	 APOLLO_330P_510L_HCI_LE_SUP_FEAT_CIS_MASTER |                                             \
	 APOLLO_330P_510L_HCI_LE_SUP_FEAT_CIS_SLAVE |                                              \
	 APOLLO_330P_510L_HCI_LE_SUP_FEAT_ISO_BROADCASTER |                                        \
	 APOLLO_330P_510L_HCI_LE_SUP_FEAT_ISO_SYNC_RECEIVER)

#define APOLLO_330P_510L_LL_FEATURES_BYTE4                                                         \
	(APOLLO_330P_510L_HCI_LE_SUP_FEAT_POWER_CONTROL_REQUEST |                                  \
	 APOLLO_330P_510L_HCI_LE_SUP_FEAT_POWER_CHANGE_IND |                                       \
	 APOLLO_330P_510L_HCI_LE_SUP_FEAT_PATH_LOSS_MONITOR |                                      \
	 APOLLO_330P_510L_HCI_LE_SUP_FEAT_PRR_ADV_ADI |                                            \
	 APOLLO_330P_510L_HCI_LE_SUP_FEAT_SUBRATING |                                              \
	 APOLLO_330P_510L_HCI_LE_SUP_FEAT_SUBRATING_HOST_SUPPORT |                                 \
	 APOLLO_330P_510L_HCI_LE_SUP_FEAT_CHAN_CLASSIFICATION)

#define APOLLO_330P_510L_LL_FEATURES_BYTE5                                                         \
	(APOLLO_330P_510L_HCI_LE_SUP_FEAT_ADV_CODING_SELECTION |                                   \
	 APOLLO_330P_510L_HCI_LE_SUP_FEAT_ADV_CODING_SELECTION_HOST_SUPPORT |                      \
	 APOLLO_330P_510L_HCI_LE_SUP_FEAT_PER_ADV_WITH_RESP_ADVERTISER |                           \
	 APOLLO_330P_510L_HCI_LE_SUP_FEAT_PER_ADV_WITH_RESP_SCANNER)

#define APOLLO_330P_510L_LL_FEATURES_BYTE6 (0ULL)
#define APOLLO_330P_510L_LL_FEATURES_BYTE7 (0ULL)

typedef enum {
	APOLLO_330P_510L_TX_POWER_LEVEL_MINUS_20P0_dBm = -20,
	APOLLO_330P_510L_TX_POWER_LEVEL_MINUS_18P0_dBm = -18,
	APOLLO_330P_510L_TX_POWER_LEVEL_MINUS_16P0_dBm = -16,
	APOLLO_330P_510L_TX_POWER_LEVEL_MINUS_14P0_dBm = -14,
	APOLLO_330P_510L_TX_POWER_LEVEL_MINUS_12P0_dBm = -12,
	APOLLO_330P_510L_TX_POWER_LEVEL_MINUS_10P0_dBm = -10,
	APOLLO_330P_510L_TX_POWER_LEVEL_MINUS_8P0_dBm = -8,
	APOLLO_330P_510L_TX_POWER_LEVEL_MINUS_6P0_dBm = -6,
	APOLLO_330P_510L_TX_POWER_LEVEL_MINUS_4P0_dBm = -4,
	APOLLO_330P_510L_TX_POWER_LEVEL_MINUS_2P0_dBm = -2,
	APOLLO_330P_510L_TX_POWER_LEVEL_0P0_dBm = 0,
	APOLLO_330P_510L_TX_POWER_LEVEL_PLUS_1P0_dBm = 1,
	APOLLO_330P_510L_TX_POWER_LEVEL_PLUS_2P0_dBm = 2,
	APOLLO_330P_510L_TX_POWER_LEVEL_PLUS_3P0_dBm = 3,
	APOLLO_330P_510L_TX_POWER_LEVEL_PLUS_4P0_dBm = 4,
	APOLLO_330P_510L_TX_POWER_LEVEL_PLUS_5P0_dBm = 5,
	APOLLO_330P_510L_TX_POWER_LEVEL_PLUS_6P0_dBm = 6,
	APOLLO_330P_510L_TX_POWER_LEVEL_PLUS_7P0_dBm = 7,
	APOLLO_330P_510L_TX_POWER_LEVEL_PLUS_8P0_dBm = 8,
	APOLLO_330P_510L_TX_POWER_LEVEL_PLUS_9P0_dBm = 9,
	APOLLO_330P_510L_TX_POWER_LEVEL_PLUS_10P0_dBm = 10,
	APOLLO_330P_510L_TX_POWER_LEVEL_PLUS_11P0_dBm = 11,
	APOLLO_330P_510L_TX_POWER_LEVEL_PLUS_12P0_dBm = 12,
	APOLLO_330P_510L_TX_POWER_LEVEL_PLUS_13P0_dBm = 13,
	APOLLO_330P_510L_TX_POWER_LEVEL_INVALID,
} apollo_330p_510l_tx_power_level_t;

#define APOLLO_330P_510L_TX_POWER_LEVEL_DEFAULT APOLLO_330P_510L_TX_POWER_LEVEL_0P0_dBm

int apollo_330p_510l_vsc_set_bd_address(const bt_addr_t *addr);
int apollo_330p_510l_vsc_get_conn_event_counter(uint16_t conn_handle);
int apollo_330p_510l_vsc_get_dtm_rssi(void);

#endif /* ZEPHYR_DRIVERS_BLUETOOTH_HCI_APOLLOX_IPC_SUPPORT_H_ */
