# Copyright (c) 2026 Ambiq Micro Inc. <www.ambiq.com>
# SPDX-License-Identifier: Apache-2.0

CONFIG_STDOUT_CONSOLE=y
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3

CONFIG_MSPI=y
CONFIG_MSPI_AMBIQ_CONTROLLER=y
CONFIG_MSPI_INIT_PRIORITY=40

CONFIG_GPIO=y
